module.exports = {
  apps: [
    {
      name: 'kbo-backend',
      cwd: 'C:/source/jdkim/kbo-dashboard',
      script: 'server/index.js',
      interpreter: 'node',
      watch: ['server'],
      ignore_watch: ['node_modules'],
      autorestart: true,
      restart_delay: 1000,
      env: { NODE_ENV: 'development', PORT: 3001 },
    },
    {
      name: 'nba-backend',
      cwd: 'C:/source/jdkim/nba-dashboard',
      script: 'server/index.js',
      interpreter: 'node',
      watch: ['server'],
      ignore_watch: ['node_modules'],
      autorestart: true,
      restart_delay: 1000,
      env: { NODE_ENV: 'development', PORT: 3002 },
    },
    {
      name: 'kbo-frontend',
      cwd: 'C:/source/jdkim/kbo-dashboard',
      script: 'node_modules/vite/bin/vite.js',
      interpreter: 'node',
      args: '--port 5173',
      watch: false,
      autorestart: true,
      restart_delay: 2000,
    },
    {
      name: 'vue-frontend',
      cwd: 'C:/source/jdkim/vue-project',
      script: 'node_modules/vite/bin/vite.js',
      interpreter: 'node',
      args: '--port 5174',
      watch: false,
      autorestart: true,
      restart_delay: 2000,
    },
  ],
}
